-- ============================================================
-- FINAL SEASON LEADERBOARD SNAPSHOT
--
-- Фиксирует полный рейтинг сезона при переходе в finished.
-- После этого исторический рейтинг не зависит от изменений
-- season_participants / predictions / profiles.
-- ============================================================


-- ============================================================
-- TABLE
-- ============================================================

create table if not exists public.season_leaderboard_snapshots (
  id bigint generated by default as identity primary key,

  season_id bigint not null
    references public.seasons(id)
    on update cascade
    on delete restrict,

  user_id uuid not null
    references auth.users(id)
    on update cascade
    on delete restrict,

  username text not null,

  rank integer not null,

  final_gp bigint not null,

  accuracy numeric not null,

  resolved_events_count integer not null,

  successful_events_count integer not null,

  created_at timestamptz not null default now(),

  constraint season_leaderboard_snapshots_rank_positive
    check (rank > 0),

  constraint season_leaderboard_snapshots_gp_nonnegative
    check (final_gp >= 0),

  constraint season_leaderboard_snapshots_accuracy_valid
    check (
      accuracy >= 0
      and accuracy <= 100
    ),

  constraint season_leaderboard_snapshots_resolved_nonnegative
    check (resolved_events_count >= 0),

  constraint season_leaderboard_snapshots_successful_nonnegative
    check (successful_events_count >= 0),

  constraint season_leaderboard_snapshots_season_rank_unique
    unique (season_id, rank),

  constraint season_leaderboard_snapshots_season_user_unique
    unique (season_id, user_id)
);


create index if not exists
  season_leaderboard_snapshots_season_id_idx
on public.season_leaderboard_snapshots (
  season_id
);


-- ============================================================
-- RLS
-- ============================================================

alter table public.season_leaderboard_snapshots
enable row level security;


drop policy if exists
  season_leaderboard_snapshots_public_select
on public.season_leaderboard_snapshots;


create policy
  season_leaderboard_snapshots_public_select
on public.season_leaderboard_snapshots
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.seasons as s
    where s.id =
      season_leaderboard_snapshots.season_id
      and s.status = 'finished'
  )
);


-- Пользовательские роли не должны менять snapshots напрямую.

revoke insert, update, delete
on public.season_leaderboard_snapshots
from anon, authenticated;

grant select
on public.season_leaderboard_snapshots
to anon, authenticated;


-- ============================================================
-- SNAPSHOT FUNCTION
-- ============================================================

create or replace function public.snapshot_finished_season_leaderboard()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin

  -- Реагируем только на реальный переход в finished.

  if new.status <> 'finished' then
    return new;
  end if;


  if old.status = 'finished' then
    return new;
  end if;


  -- На случай повторной технической попытки
  -- сначала очищаем snapshot этого сезона.

  delete from public.season_leaderboard_snapshots as sls
  where sls.season_id = new.id;


  -- Фиксируем ВСЕХ участников сезона,
  -- включая тех, кто не выполнил критерий для призов.
  --
  -- Это именно итоговый общий рейтинг.
  --
  -- username тоже сохраняется snapshot-ом:
  -- если пользователь позже изменит username,
  -- исторический результат останется таким,
  -- каким был на момент завершения сезона.

  insert into public.season_leaderboard_snapshots (
    season_id,
    user_id,
    username,
    rank,
    final_gp,
    accuracy,
    resolved_events_count,
    successful_events_count
  )

  select
    lb.season_id,
    lb.user_id,
    lb.username,
    lb.rank::integer,
    lb.balance_gp,
    lb.accuracy,
    lb.resolved_events_count,
    lb.successful_events_count

  from public.v_season_leaderboard as lb

  where lb.season_id = new.id

  order by lb.rank;


  return new;

end;
$function$;


-- ============================================================
-- TRIGGER
-- ============================================================

drop trigger if exists
  trg_snapshot_finished_season_leaderboard
on public.seasons;


create trigger
  trg_snapshot_finished_season_leaderboard

after update of status
on public.seasons

for each row

when (
  old.status is distinct from new.status
)

execute function
  public.snapshot_finished_season_leaderboard();


-- ============================================================
-- PUBLIC RPC FOR ARCHIVE
-- ============================================================

create or replace function public.get_finished_season_leaderboard(
  p_season_id bigint
)
returns table (
  rank integer,
  user_id uuid,
  username text,
  final_gp bigint,
  accuracy numeric,
  resolved_events_count integer,
  successful_events_count integer
)
language sql
stable
security definer
set search_path = ''
as $function$

  select
    sls.rank,
    sls.user_id,
    sls.username,
    sls.final_gp,
    sls.accuracy,
    sls.resolved_events_count,
    sls.successful_events_count

  from public.season_leaderboard_snapshots as sls

  join public.seasons as s
    on s.id = sls.season_id

  where sls.season_id = p_season_id
    and s.status = 'finished'

  order by sls.rank;

$function$;


revoke all
on function public.get_finished_season_leaderboard(bigint)
from public;

grant execute
on function public.get_finished_season_leaderboard(bigint)
to anon, authenticated;