-- =========================================================
-- Участие пользователя в сезоне PROGNOSIS
-- =========================================================

create table public.season_participants (
  id bigint generated by default as identity primary key,

  season_id bigint not null
    references public.seasons(id)
    on delete cascade,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  balance_gp bigint not null default 25000,

  emergency_refill_used boolean not null default false,

  points bigint not null default 0,

  predictions_count integer not null default 0,

  correct_predictions_count integer not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint season_participants_unique
    unique (season_id, user_id),

  constraint season_participants_balance_check
    check (balance_gp >= 0),

  constraint season_participants_points_check
    check (points >= 0),

  constraint season_participants_predictions_check
    check (predictions_count >= 0),

  constraint season_participants_correct_predictions_check
    check (
      correct_predictions_count >= 0
      and correct_predictions_count <= predictions_count
    )
);


-- =========================================================
-- updated_at
-- =========================================================

create trigger season_participants_set_updated_at
  before update on public.season_participants
  for each row
  execute procedure public.set_updated_at();


-- =========================================================
-- Row Level Security
-- =========================================================

alter table public.season_participants enable row level security;


create policy "Users can view own season participation"
on public.season_participants
for select
to authenticated
using ((select auth.uid()) = user_id);


-- Пока пользователь сам баланс не меняет.
-- Изменения баланса позже будут происходить через функции/RPC.


-- =========================================================
-- Grants
-- =========================================================

grant select
on table public.season_participants
to authenticated;