begin;

-- ============================================================
-- PROGNOSIS
-- Migration 001: initial database schema
--
-- Clean database architecture for the PROGNOSIS MVP.
--
-- Important:
-- - this migration is intended for a fresh development database;
-- - it must not be executed against production data;
-- - RLS policies, seed data, RPC functions and public views
--   will be created in separate migrations.
-- ============================================================
-- ============================================================
-- 1. DATABASE TYPES
-- ============================================================


-- ------------------------------------------------------------
-- User roles
-- ------------------------------------------------------------

create type public.app_role as enum (
  'user',
  'moderator',
  'admin'
);


-- ------------------------------------------------------------
-- Season lifecycle
-- ------------------------------------------------------------

create type public.season_status as enum (
  'draft',
  'scheduled',
  'active',
  'closing',
  'finished',
  'cancelled'
);


-- ------------------------------------------------------------
-- Event lifecycle
-- ------------------------------------------------------------

create type public.event_status as enum (
  'draft',
  'scheduled',
  'active',
  'closed',
  'resolving',
  'resolved',
  'cancelled',
  'void'
);


-- ------------------------------------------------------------
-- Binary prediction side
-- ------------------------------------------------------------

create type public.prediction_side as enum (
  'yes',
  'no'
);


-- ------------------------------------------------------------
-- Prediction lifecycle
-- ------------------------------------------------------------

create type public.prediction_status as enum (
  'active',
  'won',
  'lost',
  'refunded',
  'void'
);


-- ------------------------------------------------------------
-- GP transaction types
-- ------------------------------------------------------------

create type public.gp_transaction_type as enum (
  'season_initial_balance',
  'prediction_stake',
  'prediction_win',
  'prediction_loss',
  'prediction_refund',
  'emergency_bonus',
  'rewarded_ad',
  'admin_adjustment',
  'season_adjustment'
);


-- ------------------------------------------------------------
-- User event suggestion lifecycle
-- ------------------------------------------------------------

create type public.suggestion_status as enum (
  'pending',
  'under_review',
  'approved',
  'rejected',
  'implemented'
);


-- ------------------------------------------------------------
-- Ban lifecycle
-- ------------------------------------------------------------

create type public.ban_status as enum (
  'active',
  'revoked',
  'expired'
);
-- ============================================================
-- 2. CORE TABLES
-- ============================================================


-- ------------------------------------------------------------
-- Public user profiles
-- ------------------------------------------------------------

create table public.profiles (
  id uuid primary key
    references auth.users(id)
    on update cascade
    on delete cascade,

  nickname text not null,
  avatar_url text,
  role public.app_role not null default 'user',
  reputation integer not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint profiles_nickname_length
    check (
      char_length(btrim(nickname)) between 3 and 30
    ),

  constraint profiles_reputation_nonnegative
    check (reputation >= 0)
);


create unique index profiles_nickname_unique_idx
  on public.profiles (lower(btrim(nickname)));


comment on table public.profiles is
  'Public and permanent profile data for PROGNOSIS users.';


comment on column public.profiles.role is
  'Application role used for authorization and administrative access.';


comment on column public.profiles.reputation is
  'Permanent reputation accumulated across all seasons.';
  -- ------------------------------------------------------------
-- Event categories
-- ------------------------------------------------------------

create table public.event_categories (
  id bigint generated by default as identity primary key,

  code text not null,
  name text not null,
  description text,
  icon text,

  sort_order integer not null default 0,
  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint event_categories_code_format
    check (
      code ~ '^[a-z][a-z0-9_]{1,49}$'
    ),

  constraint event_categories_name_length
    check (
      char_length(btrim(name)) between 2 and 50
    ),

  constraint event_categories_sort_order_nonnegative
    check (sort_order >= 0)
);


create unique index event_categories_code_unique_idx
  on public.event_categories (lower(code));


create unique index event_categories_name_unique_idx
  on public.event_categories (lower(btrim(name)));


create index event_categories_active_sort_idx
  on public.event_categories (
    is_active,
    sort_order,
    name
  );


comment on table public.event_categories is
  'Administrator-managed categories used to classify prediction events.';
  -- ------------------------------------------------------------
-- Prediction seasons
-- ------------------------------------------------------------

create table public.seasons (
  id bigint generated by default as identity primary key,

  title text not null,
  slug text not null,
  description text,

  start_at timestamptz not null,
  end_at timestamptz not null,

  status public.season_status not null default 'draft',

  starting_balance integer not null default 25000,
  minimum_predictions_for_prize integer not null default 3,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz,

  constraint seasons_title_length
    check (
      char_length(btrim(title)) between 2 and 100
    ),

  constraint seasons_slug_format
    check (
      slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    ),

  constraint seasons_dates_valid
    check (end_at > start_at),

  constraint seasons_starting_balance_positive
    check (starting_balance > 0),

  constraint seasons_minimum_predictions_nonnegative
    check (minimum_predictions_for_prize >= 0),

  constraint seasons_closed_at_valid
    check (
      closed_at is null
      or closed_at >= start_at
    )
);


create unique index seasons_slug_unique_idx
  on public.seasons (lower(slug));


create index seasons_status_dates_idx
  on public.seasons (
    status,
    start_at,
    end_at
  );


create unique index seasons_only_one_active_idx
  on public.seasons ((status))
  where status = 'active';


comment on table public.seasons is
  'Seasonal prediction competitions. Each season grants users a new GP balance.';


comment on column public.seasons.starting_balance is
  'Initial GP balance assigned to each participant of this season.';


comment on column public.seasons.minimum_predictions_for_prize is
  'Minimum resolved predictions required to qualify for a season prize.';
  -- ------------------------------------------------------------
-- User statistics and GP balance for each season
-- ------------------------------------------------------------

create table public.user_season_stats (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references public.profiles(id)
    on update cascade
    on delete cascade,

  season_id bigint not null
    references public.seasons(id)
    on update cascade
    on delete restrict,

  gp_balance bigint not null default 25000,
  gp_locked bigint not null default 0,

  predictions_count integer not null default 0,
  resolved_predictions_count integer not null default 0,
  correct_predictions_count integer not null default 0,

  current_streak integer not null default 0,
  best_streak integer not null default 0,

  emergency_bonus_used boolean not null default false,

  capital_reached_at timestamptz not null default now(),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint user_season_stats_user_season_unique
    unique (user_id, season_id),

  constraint user_season_stats_gp_balance_nonnegative
    check (gp_balance >= 0),

  constraint user_season_stats_gp_locked_nonnegative
    check (gp_locked >= 0),

  constraint user_season_stats_predictions_nonnegative
    check (predictions_count >= 0),

  constraint user_season_stats_resolved_nonnegative
    check (resolved_predictions_count >= 0),

  constraint user_season_stats_correct_nonnegative
    check (correct_predictions_count >= 0),

  constraint user_season_stats_resolved_not_above_total
    check (
      resolved_predictions_count <= predictions_count
    ),

  constraint user_season_stats_correct_not_above_resolved
    check (
      correct_predictions_count <= resolved_predictions_count
    ),

  constraint user_season_stats_current_streak_nonnegative
    check (current_streak >= 0),

  constraint user_season_stats_best_streak_nonnegative
    check (best_streak >= 0),

  constraint user_season_stats_best_streak_valid
    check (best_streak >= current_streak)
);


create index user_season_stats_user_idx
  on public.user_season_stats (user_id);


create index user_season_stats_season_idx
  on public.user_season_stats (season_id);


create index user_season_stats_leaderboard_idx
  on public.user_season_stats (
    season_id,
    gp_balance desc,
    correct_predictions_count desc,
    resolved_predictions_count desc,
    capital_reached_at asc
  );


comment on table public.user_season_stats is
  'Stores each user GP balance and prediction statistics for one season.';


comment on column public.user_season_stats.gp_balance is
  'GP currently available for placing predictions.';


comment on column public.user_season_stats.gp_locked is
  'GP locked in unresolved predictions.';


comment on column public.user_season_stats.capital_reached_at is
  'Time when the user most recently reached the current capital, used as the final leaderboard tiebreaker.';
  -- ============================================================
-- 3. PREDICTION MARKET CORE
-- ============================================================


-- ------------------------------------------------------------
-- Prediction events
-- ------------------------------------------------------------

create table public.events (
  id bigint generated by default as identity primary key,

  season_id bigint not null
    references public.seasons(id)
    on update cascade
    on delete restrict,

  category_id bigint not null
    references public.event_categories(id)
    on update cascade
    on delete restrict,

  title text not null,
  slug text not null,
  description text,

  source_name text,
  source_url text,
  resolution_rule text not null,

  publish_at timestamptz not null,
  prediction_close_at timestamptz not null,
  expected_resolution_at timestamptz,

  resolved_at timestamptz,

  status public.event_status not null default 'draft',
  result public.prediction_side,

  cancel_reason text,
  is_featured boolean not null default false,

  predictions_count integer not null default 0,
  volume_gp bigint not null default 0,

  created_by uuid
    references public.profiles(id)
    on update cascade
    on delete set null,

  resolved_by uuid
    references public.profiles(id)
    on update cascade
    on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint events_title_length
    check (
      char_length(btrim(title)) between 5 and 250
    ),

  constraint events_slug_format
    check (
      slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    ),

  constraint events_resolution_rule_length
    check (
      char_length(btrim(resolution_rule)) between 10 and 2000
    ),

  constraint events_prediction_close_after_publish
    check (
      prediction_close_at > publish_at
    ),

  constraint events_resolution_after_close
    check (
      expected_resolution_at is null
      or expected_resolution_at >= prediction_close_at
    ),

  constraint events_resolved_at_valid
    check (
      resolved_at is null
      or resolved_at >= prediction_close_at
    ),

  constraint events_predictions_count_nonnegative
    check (
      predictions_count >= 0
    ),

  constraint events_volume_gp_nonnegative
    check (
      volume_gp >= 0
    ),

  constraint events_result_required_when_resolved
    check (
      status <> 'resolved'
      or result is not null
    ),

  constraint events_result_empty_when_not_resolved
    check (
      status = 'resolved'
      or result is null
    ),

  constraint events_cancel_reason_required
    check (
      status not in ('cancelled', 'void')
      or char_length(btrim(coalesce(cancel_reason, ''))) >= 5
    )
);


create unique index events_slug_unique_idx
  on public.events (lower(slug));


create index events_season_status_idx
  on public.events (
    season_id,
    status
  );


create index events_category_status_idx
  on public.events (
    category_id,
    status
  );


create index events_public_feed_idx
  on public.events (
    status,
    publish_at desc,
    prediction_close_at
  );


create index events_featured_idx
  on public.events (
    is_featured,
    publish_at desc
  )
  where is_featured = true;


comment on table public.events is
  'Binary prediction events published within a PROGNOSIS season.';


comment on column public.events.resolution_rule is
  'Objective rule describing how the event result must be determined.';


comment on column public.events.predictions_count is
  'Cached number of accepted predictions for this event.';


comment on column public.events.volume_gp is
  'Cached total GP staked on this event.';
  -- ------------------------------------------------------------
-- Event liquidity pools
-- ------------------------------------------------------------

create table public.event_pools (
  event_id bigint primary key
    references public.events(id)
    on update cascade
    on delete cascade,

  yes_pool bigint not null default 1000,
  no_pool bigint not null default 1000,

  updated_at timestamptz not null default now(),

  constraint event_pools_yes_pool_positive
    check (
      yes_pool > 0
    ),

  constraint event_pools_no_pool_positive
    check (
      no_pool > 0
    )
);


comment on table public.event_pools is
  'Stores source liquidity values used to calculate live prediction odds.';


comment on column public.event_pools.yes_pool is
  'Current GP liquidity assigned to the YES side.';


comment on column public.event_pools.no_pool is
  'Current GP liquidity assigned to the NO side.';
  -- ------------------------------------------------------------
-- User predictions
-- ------------------------------------------------------------

create table public.predictions (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references public.profiles(id)
    on update cascade
    on delete restrict,

  season_id bigint not null
    references public.seasons(id)
    on update cascade
    on delete restrict,

  event_id bigint not null
    references public.events(id)
    on update cascade
    on delete restrict,

  prediction_side public.prediction_side not null,

  stake_amount bigint not null,
  odds_at_purchase numeric(10, 4) not null,

  potential_payout bigint not null,
  actual_payout bigint,

  status public.prediction_status not null default 'active',

  placed_at timestamptz not null default now(),
  resolved_at timestamptz,

  created_at timestamptz not null default now(),

  constraint predictions_user_event_unique
    unique (user_id, event_id),

  constraint predictions_stake_positive
    check (
      stake_amount > 0
    ),

  constraint predictions_odds_valid
    check (
      odds_at_purchase >= 1
      and odds_at_purchase <= 10
    ),

  constraint predictions_potential_payout_valid
    check (
      potential_payout >= stake_amount
    ),

  constraint predictions_actual_payout_nonnegative
    check (
      actual_payout is null
      or actual_payout >= 0
    ),

  constraint predictions_resolution_fields_valid
    check (
      (
        status = 'active'
        and resolved_at is null
        and actual_payout is null
      )
      or
      (
        status <> 'active'
        and resolved_at is not null
        and actual_payout is not null
      )
    ),

  constraint predictions_won_payout_valid
    check (
      status <> 'won'
      or actual_payout > 0
    ),

  constraint predictions_lost_payout_valid
    check (
      status <> 'lost'
      or actual_payout = 0
    ),

  constraint predictions_refund_payout_valid
    check (
      status not in ('refunded', 'void')
      or actual_payout = stake_amount
    )
);


create index predictions_user_placed_idx
  on public.predictions (
    user_id,
    placed_at desc
  );


create index predictions_event_status_idx
  on public.predictions (
    event_id,
    status
  );


create index predictions_season_user_idx
  on public.predictions (
    season_id,
    user_id
  );


create index predictions_active_event_idx
  on public.predictions (
    event_id,
    prediction_side
  )
  where status = 'active';


comment on table public.predictions is
  'Immutable prediction positions created through protected server-side functions.';


comment on column public.predictions.odds_at_purchase is
  'Odds permanently fixed at the moment the prediction is accepted.';


comment on column public.predictions.potential_payout is
  'Maximum GP payout calculated when the prediction is placed.';


comment on column public.predictions.actual_payout is
  'Final GP amount returned or awarded after resolution.';
  -- ------------------------------------------------------------
-- Immutable GP transaction ledger
-- ------------------------------------------------------------

create table public.gp_transactions (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references public.profiles(id)
    on update cascade
    on delete restrict,

  season_id bigint not null
    references public.seasons(id)
    on update cascade
    on delete restrict,

  prediction_id bigint
    references public.predictions(id)
    on update cascade
    on delete restrict,

  event_id bigint
    references public.events(id)
    on update cascade
    on delete restrict,

  transaction_type public.gp_transaction_type not null,

  amount_available bigint not null default 0,
  amount_locked bigint not null default 0,

  balance_available_after bigint not null,
  balance_locked_after bigint not null,

  idempotency_key text not null,
  description text,
  metadata jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),

  constraint gp_transactions_has_balance_change
    check (
      amount_available <> 0
      or amount_locked <> 0
    ),

  constraint gp_transactions_available_balance_nonnegative
    check (
      balance_available_after >= 0
    ),

  constraint gp_transactions_locked_balance_nonnegative
    check (
      balance_locked_after >= 0
    ),

  constraint gp_transactions_idempotency_key_length
    check (
      char_length(btrim(idempotency_key)) between 8 and 200
    ),

  constraint gp_transactions_metadata_object
    check (
      jsonb_typeof(metadata) = 'object'
    )
);


create unique index gp_transactions_idempotency_unique_idx
  on public.gp_transactions (idempotency_key);


create index gp_transactions_user_history_idx
  on public.gp_transactions (
    user_id,
    created_at desc
  );


create index gp_transactions_season_history_idx
  on public.gp_transactions (
    season_id,
    created_at desc
  );


create index gp_transactions_prediction_idx
  on public.gp_transactions (prediction_id)
  where prediction_id is not null;


create index gp_transactions_event_idx
  on public.gp_transactions (event_id)
  where event_id is not null;


comment on table public.gp_transactions is
  'Immutable ledger recording every change to available and locked GP balances.';


comment on column public.gp_transactions.amount_available is
  'Change applied to the user available GP balance.';


comment on column public.gp_transactions.amount_locked is
  'Change applied to the user locked GP balance.';


comment on column public.gp_transactions.idempotency_key is
  'Unique operation key preventing accidental duplicate financial processing.';
  -- ============================================================
-- 4. REWARDS AND REPUTATION
-- ============================================================


-- ------------------------------------------------------------
-- Season prizes
-- ------------------------------------------------------------

create table public.season_prizes (
  id bigint generated by default as identity primary key,

  season_id bigint not null
    references public.seasons(id)
    on update cascade
    on delete cascade,

  place integer not null,

  title text not null,
  description text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint season_prizes_place_positive
    check (
      place > 0
    ),

  constraint season_prizes_title_length
    check (
      char_length(btrim(title)) between 2 and 150
    ),

  constraint season_prizes_season_place_unique
    unique (season_id, place)
);


create index season_prizes_season_idx
  on public.season_prizes (
    season_id,
    place
  );


comment on table public.season_prizes is
  'Prize configuration for ranking places within a specific season.';


comment on column public.season_prizes.place is
  'Final leaderboard place eligible for this prize.';
  -- ------------------------------------------------------------
-- Historical season winners
-- ------------------------------------------------------------

create table public.season_winners (
  id bigint generated by default as identity primary key,

  season_id bigint not null
    references public.seasons(id)
    on update cascade
    on delete restrict,

  user_id uuid not null
    references public.profiles(id)
    on update cascade
    on delete restrict,

  prize_id bigint
    references public.season_prizes(id)
    on update cascade
    on delete set null,

  place integer not null,

  final_gp bigint not null,
  accuracy numeric(7, 4) not null,
  predictions_count integer not null,

  prize_title_snapshot text,
  prize_description_snapshot text,

  created_at timestamptz not null default now(),

  constraint season_winners_place_positive
    check (
      place > 0
    ),

  constraint season_winners_final_gp_nonnegative
    check (
      final_gp >= 0
    ),

  constraint season_winners_accuracy_valid
    check (
      accuracy >= 0
      and accuracy <= 100
    ),

  constraint season_winners_predictions_nonnegative
    check (
      predictions_count >= 0
    ),

  constraint season_winners_season_place_unique
    unique (season_id, place),

  constraint season_winners_season_user_unique
    unique (season_id, user_id)
);


create index season_winners_user_idx
  on public.season_winners (
    user_id,
    created_at desc
  );


create index season_winners_season_idx
  on public.season_winners (
    season_id,
    place
  );


comment on table public.season_winners is
  'Immutable historical snapshot of final season winners and awarded prizes.';


comment on column public.season_winners.final_gp is
  'User final available GP at the moment the season was closed.';


comment on column public.season_winners.accuracy is
  'Prediction accuracy snapshot expressed as a percentage from 0 to 100.';


comment on column public.season_winners.prize_title_snapshot is
  'Prize title copied at award time so historical records do not change later.';
  -- ------------------------------------------------------------
-- Achievement catalogue
-- ------------------------------------------------------------

create table public.achievements (
  id bigint generated by default as identity primary key,

  code text not null,
  title text not null,
  description text not null,
  icon text,

  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint achievements_code_format
    check (
      code ~ '^[a-z][a-z0-9_]{1,49}$'
    ),

  constraint achievements_title_length
    check (
      char_length(btrim(title)) between 2 and 100
    ),

  constraint achievements_description_length
    check (
      char_length(btrim(description)) between 5 and 1000
    )
);


create unique index achievements_code_unique_idx
  on public.achievements (
    lower(code)
  );


create unique index achievements_title_unique_idx
  on public.achievements (
    lower(btrim(title))
  );


create index achievements_active_idx
  on public.achievements (
    is_active,
    title
  );


comment on table public.achievements is
  'Catalogue of permanent and seasonal achievements available in PROGNOSIS.';
  -- ------------------------------------------------------------
-- Achievements awarded to users
-- ------------------------------------------------------------

create table public.user_achievements (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references public.profiles(id)
    on update cascade
    on delete cascade,

  achievement_id bigint not null
    references public.achievements(id)
    on update cascade
    on delete restrict,

  season_id bigint
    references public.seasons(id)
    on update cascade
    on delete restrict,

  awarded_at timestamptz not null default now(),

  metadata jsonb not null default '{}'::jsonb,

  constraint user_achievements_metadata_object
    check (
      jsonb_typeof(metadata) = 'object'
    )
);


create unique index user_achievements_global_unique_idx
  on public.user_achievements (
    user_id,
    achievement_id
  )
  where season_id is null;


create unique index user_achievements_season_unique_idx
  on public.user_achievements (
    user_id,
    achievement_id,
    season_id
  )
  where season_id is not null;


create index user_achievements_user_idx
  on public.user_achievements (
    user_id,
    awarded_at desc
  );


create index user_achievements_season_idx
  on public.user_achievements (
    season_id,
    awarded_at desc
  )
  where season_id is not null;


comment on table public.user_achievements is
  'Achievements awarded to users globally or within a specific season.';


comment on column public.user_achievements.season_id is
  'Null for permanent one-time achievements; populated for seasonal achievements.';
  -- ------------------------------------------------------------
-- Reputation levels
-- ------------------------------------------------------------

create table public.reputation_levels (
  id bigint generated by default as identity primary key,

  code text not null,
  title text not null,
  description text,
  icon text,

  min_reputation integer not null,
  max_reputation integer,

  sort_order integer not null default 0,
  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint reputation_levels_code_format
    check (
      code ~ '^[a-z][a-z0-9_]{1,49}$'
    ),

  constraint reputation_levels_title_length
    check (
      char_length(btrim(title)) between 2 and 100
    ),

  constraint reputation_levels_min_nonnegative
    check (
      min_reputation >= 0
    ),

  constraint reputation_levels_range_valid
    check (
      max_reputation is null
      or max_reputation >= min_reputation
    ),

  constraint reputation_levels_sort_nonnegative
    check (
      sort_order >= 0
    )
);


create unique index reputation_levels_code_unique_idx
  on public.reputation_levels (
    lower(code)
  );


create unique index reputation_levels_title_unique_idx
  on public.reputation_levels (
    lower(btrim(title))
  );


create index reputation_levels_range_idx
  on public.reputation_levels (
    min_reputation,
    max_reputation
  );


create index reputation_levels_active_sort_idx
  on public.reputation_levels (
    is_active,
    sort_order
  );


comment on table public.reputation_levels is
  'Configured reputation level ranges displayed in user profiles.';


comment on column public.reputation_levels.max_reputation is
  'Upper inclusive boundary. Null means the level has no upper limit.';
  -- ============================================================
-- 5. USER AND SYSTEM SUPPORT TABLES
-- ============================================================


-- ------------------------------------------------------------
-- User notifications
-- ------------------------------------------------------------

create table public.notifications (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references public.profiles(id)
    on update cascade
    on delete cascade,

  type text not null,
  title text not null,
  message text not null,
  link text,

  is_read boolean not null default false,
  read_at timestamptz,

  created_at timestamptz not null default now(),

  constraint notifications_type_length
    check (
      char_length(btrim(type)) between 2 and 50
    ),

  constraint notifications_title_length
    check (
      char_length(btrim(title)) between 2 and 150
    ),

  constraint notifications_message_length
    check (
      char_length(btrim(message)) between 2 and 2000
    ),

  constraint notifications_read_state_valid
    check (
      (
        is_read = false
        and read_at is null
      )
      or
      (
        is_read = true
        and read_at is not null
      )
    )
);


create index notifications_user_created_idx
  on public.notifications (
    user_id,
    created_at desc
  );


create index notifications_user_unread_idx
  on public.notifications (
    user_id,
    created_at desc
  )
  where is_read = false;


comment on table public.notifications is
  'System notifications delivered to individual PROGNOSIS users.';


comment on column public.notifications.link is
  'Optional internal application path associated with the notification.';
  -- ------------------------------------------------------------
-- User-submitted event suggestions
-- ------------------------------------------------------------

create table public.event_suggestions (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references public.profiles(id)
    on update cascade
    on delete cascade,

  category_id bigint
    references public.event_categories(id)
    on update cascade
    on delete set null,

  title text not null,
  description text,
  source_url text,

  status public.suggestion_status not null default 'pending',

  admin_comment text,

  reviewed_by uuid
    references public.profiles(id)
    on update cascade
    on delete set null,

  reviewed_at timestamptz,

  implemented_event_id bigint
    references public.events(id)
    on update cascade
    on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint event_suggestions_title_length
    check (
      char_length(btrim(title)) between 5 and 250
    ),

  constraint event_suggestions_description_length
    check (
      description is null
      or char_length(btrim(description)) between 10 and 3000
    ),

  constraint event_suggestions_review_state_valid
    check (
      (
        status in ('pending', 'under_review')
        and reviewed_at is null
      )
      or
      (
        status in ('approved', 'rejected', 'implemented')
        and reviewed_at is not null
      )
    ),

  constraint event_suggestions_implemented_event_valid
    check (
      status <> 'implemented'
      or implemented_event_id is not null
    )
);


create index event_suggestions_user_idx
  on public.event_suggestions (
    user_id,
    created_at desc
  );


create index event_suggestions_status_idx
  on public.event_suggestions (
    status,
    created_at
  );


create index event_suggestions_category_idx
  on public.event_suggestions (
    category_id,
    created_at desc
  )
  where category_id is not null;


comment on table public.event_suggestions is
  'Prediction event ideas submitted by registered users for administrative review.';
  -- ------------------------------------------------------------
-- User bans
-- ------------------------------------------------------------

create table public.user_bans (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references public.profiles(id)
    on update cascade
    on delete cascade,

  status public.ban_status not null default 'active',

  reason text not null,
  ban_type text not null default 'general',

  banned_by uuid
    references public.profiles(id)
    on update cascade
    on delete set null,

  banned_at timestamptz not null default now(),
  banned_until timestamptz,
  is_permanent boolean not null default false,

  revoked_at timestamptz,

  revoked_by uuid
    references public.profiles(id)
    on update cascade
    on delete set null,

  revocation_reason text,

  metadata jsonb not null default '{}'::jsonb,

  constraint user_bans_reason_length
    check (
      char_length(btrim(reason)) between 5 and 2000
    ),

  constraint user_bans_type_length
    check (
      char_length(btrim(ban_type)) between 2 and 50
    ),

  constraint user_bans_duration_valid
    check (
      (
        is_permanent = true
        and banned_until is null
      )
      or
      (
        is_permanent = false
        and banned_until is not null
        and banned_until > banned_at
      )
    ),

  constraint user_bans_revocation_valid
    check (
      (
        status = 'revoked'
        and revoked_at is not null
      )
      or
      (
        status <> 'revoked'
        and revoked_at is null
      )
    ),

  constraint user_bans_metadata_object
    check (
      jsonb_typeof(metadata) = 'object'
    )
);


create index user_bans_user_idx
  on public.user_bans (
    user_id,
    banned_at desc
  );


create index user_bans_active_idx
  on public.user_bans (
    user_id,
    banned_until
  )
  where status = 'active';


comment on table public.user_bans is
  'Historical record of temporary and permanent user access restrictions.';


comment on column public.user_bans.status is
  'Lifecycle state of the ban: active, revoked, or expired.';
  -- ------------------------------------------------------------
-- User security and anti-fraud events
-- ------------------------------------------------------------

create table public.user_security_events (
  id bigint generated by default as identity primary key,

  user_id uuid
    references public.profiles(id)
    on update cascade
    on delete set null,

  event_type text not null,

  ip_hash text,
  device_hash text,

  risk_score integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),

  constraint user_security_events_type_length
    check (
      char_length(btrim(event_type)) between 2 and 100
    ),

  constraint user_security_events_risk_score_valid
    check (
      risk_score between 0 and 100
    ),

  constraint user_security_events_metadata_object
    check (
      jsonb_typeof(metadata) = 'object'
    )
);


create index user_security_events_user_idx
  on public.user_security_events (
    user_id,
    created_at desc
  )
  where user_id is not null;


create index user_security_events_type_idx
  on public.user_security_events (
    event_type,
    created_at desc
  );


create index user_security_events_high_risk_idx
  on public.user_security_events (
    risk_score desc,
    created_at desc
  )
  where risk_score >= 70;


comment on table public.user_security_events is
  'Private anti-fraud and security event log. Raw IP addresses and device identifiers must not be stored here.';


comment on column public.user_security_events.ip_hash is
  'Hashed or pseudonymized network identifier; never a raw IP address.';


comment on column public.user_security_events.device_hash is
  'Hashed or pseudonymized device identifier.';
  -- ------------------------------------------------------------
-- Administrative audit log
-- ------------------------------------------------------------

create table public.audit_logs (
  id bigint generated by default as identity primary key,

  actor_id uuid
    references public.profiles(id)
    on update cascade
    on delete set null,

  action text not null,
  entity_type text not null,
  entity_id text,

  old_data jsonb,
  new_data jsonb,
  metadata jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),

  constraint audit_logs_action_length
    check (
      char_length(btrim(action)) between 2 and 100
    ),

  constraint audit_logs_entity_type_length
    check (
      char_length(btrim(entity_type)) between 2 and 100
    ),

  constraint audit_logs_old_data_object
    check (
      old_data is null
      or jsonb_typeof(old_data) = 'object'
    ),

  constraint audit_logs_new_data_object
    check (
      new_data is null
      or jsonb_typeof(new_data) = 'object'
    ),

  constraint audit_logs_metadata_object
    check (
      jsonb_typeof(metadata) = 'object'
    )
);


create index audit_logs_actor_idx
  on public.audit_logs (
    actor_id,
    created_at desc
  )
  where actor_id is not null;


create index audit_logs_entity_idx
  on public.audit_logs (
    entity_type,
    entity_id,
    created_at desc
  );


create index audit_logs_action_idx
  on public.audit_logs (
    action,
    created_at desc
  );


comment on table public.audit_logs is
  'Append-only audit trail for administrative and sensitive system operations.';
  -- ------------------------------------------------------------
-- Application settings
-- ------------------------------------------------------------

create table public.system_settings (
  key text primary key,

  value jsonb not null,
  description text,

  is_public boolean not null default false,

  updated_by uuid
    references public.profiles(id)
    on update cascade
    on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint system_settings_key_format
    check (
      key ~ '^[a-z][a-z0-9_.]{1,99}$'
    )
);


create index system_settings_public_idx
  on public.system_settings (
    key
  )
  where is_public = true;


comment on table public.system_settings is
  'Typed application configuration stored as JSON values.';


comment on column public.system_settings.is_public is
  'Controls whether unauthenticated and regular users may read the setting.';
  -- ============================================================
-- 6. COMMON FUNCTIONS
-- ============================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as
$$
begin
    new.updated_at = now();
    return new;
end;
$$;
-- ============================================================
-- updated_at triggers
-- ============================================================

create trigger trg_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();


create trigger trg_event_categories_updated_at
before update on public.event_categories
for each row
execute function public.set_updated_at();


create trigger trg_seasons_updated_at
before update on public.seasons
for each row
execute function public.set_updated_at();


create trigger trg_user_season_stats_updated_at
before update on public.user_season_stats
for each row
execute function public.set_updated_at();


create trigger trg_events_updated_at
before update on public.events
for each row
execute function public.set_updated_at();


create trigger trg_event_pools_updated_at
before update on public.event_pools
for each row
execute function public.set_updated_at();


create trigger trg_season_prizes_updated_at
before update on public.season_prizes
for each row
execute function public.set_updated_at();


create trigger trg_achievements_updated_at
before update on public.achievements
for each row
execute function public.set_updated_at();


create trigger trg_reputation_levels_updated_at
before update on public.reputation_levels
for each row
execute function public.set_updated_at();


create trigger trg_event_suggestions_updated_at
before update on public.event_suggestions
for each row
execute function public.set_updated_at();


create trigger trg_system_settings_updated_at
before update on public.system_settings
for each row
execute function public.set_updated_at();
-- ============================================================
-- Row Level Security
-- ============================================================

alter table public.profiles enable row level security;

alter table public.event_categories enable row level security;

alter table public.seasons enable row level security;

alter table public.user_season_stats enable row level security;

alter table public.events enable row level security;

alter table public.event_pools enable row level security;

alter table public.predictions enable row level security;

alter table public.gp_transactions enable row level security;

alter table public.season_prizes enable row level security;

alter table public.season_winners enable row level security;

alter table public.achievements enable row level security;

alter table public.user_achievements enable row level security;

alter table public.reputation_levels enable row level security;

alter table public.notifications enable row level security;

alter table public.event_suggestions enable row level security;

alter table public.user_bans enable row level security;

alter table public.user_security_events enable row level security;

alter table public.audit_logs enable row level security;

alter table public.system_settings enable row level security;

commit;